name: Maven CI

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Prepare Maven wrapper
        run: |
          sed -i 's/\r$//' mvnw
          chmod +x mvnw

      - name: Run Maven tests
        run: ./mvnw -B -ntp test
